spring.application.name=customizer


spring.ai.ollama.base-url=http://localhost:11434
spring.ai.model.chat=ollama
spring.ai.ollama.chat.model=gemma4
spring.ai.chat.client.enabled=true
spring.ai.ollama.chat.temperature=0.6