spring.application.name=dbtools

spring.ai.ollama.base-url=http://localhost:11434
spring.ai.model.chat=ollama
spring.ai.ollama.chat.model=gemma4
spring.ai.chat.client.enabled=true
spring.ai.ollama.chat.temperature=0.6


# spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:postgresql://localhost:5432/dbtools
spring.datasource.username=userdb
spring.datasource.password=duke
spring.datasource.driver-class-name=org.postgresql.Driver

spring.docker.compose.file=/home/mejiad/ai-101/compose.yaml
# Solo levanta el servicio
spring.docker.compose.lifecycle-management=start-only

spring.sql.init.data-locations=classpath:db/data.sql
spring.jpa.defer-datasource-initialization=true
spring.jpa.show-sql=true
spring.sql.init.mode=always
spring.jpa.hibernate.ddl-auto=create
