spring.application.name=vectordb

spring.ai.model.embeddings=ollama
spring.ai.ollama.base-url=http://localhost:11434
spring.ai.ollama.embedding.model=mxbai-embed-large


spring.ai.vectorstore.qdrant.host=localhost
spring.ai.vectorstore.qdrant.port=6334
spring.ai.vectorstore.qdrant.collection-name=vector_store
spring.ai.vectorstore.qdrant.content-field-name=doc_content
spring.ai.vectorstore.qdrant.use-tls=false
spring.ai.vectorstore.qdrant.initialize-schema=true



# spring.ai.vectorstore.qdrant.api-key:<qdrant api key>
