spring.application.name=rag

spring.ai.ollama.base-url=http://localhost:11434
spring.ai.model.chat=ollama
spring.ai.ollama.chat.model=gemma4
spring.ai.chat.client.enabled=true
spring.ai.ollama.chat.temperature=0.6

spring.ai.model.embedding=ollama
spring.ai.ollama.embedding.model=mxbai-embed-large

spring.ai.vectorstore.qdrant.host=localhost
spring.ai.vectorstore.qdrant.port=6334
spring.ai.vectorstore.qdrant.collection-name=vector_store
spring.ai.vectorstore.qdrant.content-field-name=doc_content
spring.ai.vectorstore.qdrant.use-tls=false
spring.ai.vectorstore.qdrant.initialize-schema=true

# application.properties de Proyecto B
spring.docker.compose.file=/home/mejiad/ai-101/compose.yaml
# Solo levanta el servicio
spring.docker.compose.lifecycle-management=start-only
